export const GET_PRODUCTS = 'GET_PRODUCTS'
export const SHOW_PRODUCTS = 'SHOW_PRODUCTS'
export const SHOW_ITEM = 'SHOW_ITEM'
export const CHANGE_SEARCHBOX = 'CHANGE_SEARCHBOX'
export const SET_ITEM = 'SET_ITEM'
export const CLEAN_PRODUCTS = 'CLEAN_PRODUCTS'
export const CLEAN_ITEMS = 'CLEAN_ITEMS'